### ISSUE TITLE
Style Users List Table

### ISSUE THREAD

**Issue by ChexWarrior** [cs691projecthotspots/webapp#39]
The table at `/users/admin` isn't styled properly, it should match the rest of the site styles.

**Comment by ChexWarrior** [comment]
@perryc85 You mind tackling this one?

**Comment by perryc85** [comment]
Yeah, I can take it.

**Comment by perryc85** [comment]
@ChexWarrior - is the admin email `admin@hotspots.local`? and password `password`?

**Comment by perryc85** [comment]
@ChexWarrior - NVW. We spoke on the phone.
