### ISSUE TITLE
Update Site Styles

### ISSUE THREAD

**Issue by ChexWarrior** [cs691projecthotspots/webapp#6]
The site is currently very bare from a design stand point, some refactoring of the styles need to be found.

**Comment by perryc85** [comment]
Totally agree! I was thinking of a lighter theme? Something more inviting and live!!

**Comment by ChexWarrior** [comment]
@perryc85 Currently I'm using Bulma CSS as a framework, you can opt to change this if you want but you'll need to work with me to rework some of the Twig templates.

**Comment by perryc85** [comment]
@ChexWarrior - I will just look over Bulma.

**Comment by perryc85** [comment]
@ChexWarrior - Is changing colors a tough task or could I go into the code and replace things?

**Comment by ChexWarrior** [comment]
@perryc85 Changing colors is easy! I recommend you read over the [Bulma docs](https://bulma.io/documentation/) (just start at the beginning and read through the whole thing...).  You'll also need to know [SASS](https://sass-lang.com/) to use Bulma effectively, I wouldn't worry, SASS is really just a better version of CSS.

**Comment by perryc85** [comment]
@ChexWarrior Okay. I will try to pick up SASS. I've never worked with it. I'll figure it out.

**Comment by kd90693n** [comment]
@perryc85 I'm surprised you Professor Haik didn't go over it. He kept saying to use sass and not css for cross-browser styling.

**Comment by perryc85** [comment]
@kd90693n - There was also a version with some wacky extension in Ionic/Angular.

**Comment by ChexWarrior** [comment]
@perryc85 Don't worry about SASS, focus on Bulma, SASS is really easy to pick up, again its really just easier CSS.

**Comment by perryc85** [comment]
@ChexWarrior - Dumb question that I pretty much know, but I'll ask anyway. You installed Bulma and configured it to be apart of Homestead?

**Comment by ChexWarrior** [comment]
That's correct, read the installation instructions for Bulma and you'll see its installed through NPM. Check the `package.json` file for details.

**Comment by perryc85** [comment]
@ChexWarrior - It's all clear now.  👍 It's a benefit of using virtual environments.

**Comment by ChexWarrior** [comment]
It's a benefit of using package managers such as Composer and NPM.

**Comment by perryc85** [comment]
That too!

**Comment by kd90693n** [comment]
@ChexWarrior padding: 0px 15px 0px; for the nav. Can you align the search bar to the logo with similar padding.

**Comment by ChexWarrior** [comment]
@kd90693n @perryc85 Nice work today guys, we got a lot done.  Remember from now on you'll want to run this command when pulling from master `npx node-sass public/assets/sass/styles.scss public/assets/css/styles.css` to ensure you styles are update to date.  

Also remember that any overrides or new variables you want to make should be in the `public/assets/sass/variables.scss` file!

**Comment by ChexWarrior** [comment]
@perryc85 @kd90693n In your guy's estimation what else do you think needs to be done for this?

**Comment by kd90693n** [comment]
@ChexWarrior I think by Tuesday after our meeting it should be complete. I wanted to make one edit to the activities so it has a card kind of style. I can get this done tonight but want to give Charles Tuesday in case he wants to change something else. We can go page by page with him to see what other changes are needed. I still need to fix the profile button, I deleted the styles to avoid conflicting with Bibin yesterday.

http://versions.bulma.io/0.7.0/documentation/components/card/
https://bulma.io/documentation/elements/box/

**Comment by perryc85** [comment]
Yes, I'd like to make final style edits tommorow

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ChexWarrior** [comment]
@perryc85 @kd90693n Are we feeling that this issue is completed? Are there any other things you want to do before closing?
