### ISSUE TITLE
Understand and Handle Session Refresh for User Profile Change

### ISSUE THREAD

**Issue by ChexWarrior** [cs691projecthotspots/webapp#69]
While doing a demo run through I ran into a bug that whenever I got a validation error on the user profile page (except for password) the user would get logged out.  I did some digging and found the relevant bit of documentation [here](https://symfony.com/doc/current/security/user_provider.html#entity-user-provider). I'm still struggling to understand why exactly the validation errors are causing the user to get logged out, however I have a workaround until I can discover the fix.

**Comment by kd90693n** [comment]
Interesting, I didn't see this issue in previous iterations when we tested for modify profile info.

**Comment by ChexWarrior** [comment]
If that's true then maybe we can discover when the bug was introduced using [git bisect](https://git-scm.com/docs/git-bisect).

**Comment by ChexWarrior** [comment]
Okay fixed it, due to how Symfony handles form submission the users password property would be blanked out causing Symfony to think the user had changed therefore causing the logout.  I've updated the profile controller to always set a users password.
