### ISSUE TITLE
Modify User Profile Information

### ISSUE THREAD

**Issue by ChexWarrior** [cs691projecthotspots/webapp#7]
* Add validation to the various user fields on profile
* Display error and success messages when saving profile

**Comment by ChexWarrior** [comment]
Remaining work
- Ensure password isn't changed unless user actually enters value in form
- Style field error messages
- Show success message when profile saved

**Comment by ChexWarrior** [comment]
@kd90693n I've finished the remaining tasks, want to give it one last test?

**Comment by kd90693n** [comment]
Yup, I'll test it now.

**Comment by kd90693n** [comment]
Test case: submission confirmation | Passed
Test case: email change without password | Failed
Test case: email change with password | Passed
Test case: email address without "@" symbol | Passed (error message displays, is it from the browser though)
Test case: email address without "@" symbol with novalidate on label | Passed (error message displays)
Test case: email address without .com | Passed (error message displays)
Test case: latitude "-91" longitude "3" | Passed (error message displays) 
Test case: latitude "91" longitude "3" | Passed (error message displays)
Test case: latitude "90" longitude "3" | Passed
Test case: latitude "30" longitude "-181" | Passed (error message displays)
Test case: latitude "30" longitude "181" | Passed (error message displays)
Test case: latitude "30" longitude "180" | Passed
Test case: latitude "30" longitude "-180" | Passed
Test case: First Name is blank | Sorta Passed (error message displays)
                     - name displayed above gets replaced: "Kevin Delgado's Profile" to "Delgado's Profile"
Test case: Last Name is blank | Sorta Passed (error message displays)
                     - name displayed above gets replaced: "Kevin Delgado's Profile" to "Kevin 's Profile"
Test case: First and Last Name is blank |  | Passed (error message displays on both)
Test case: Latitude and Longitude is blank | Passed (null/blank is acceptable, optional field)
Test case: Latitude and Longitude "-200" | Passed (error message displays on both)
Test case: First Name & Last Name are blank AND Latitude & Longitude "-201"  | Passed (error message displays on all fields)

**Comment by kd90693n** [comment]
@procrasprincess @Koshygkoshy the above may help with the test designs.

**Comment by ChexWarrior** [comment]
The code has been merged.
