### ISSUE TITLE
Activities: Search and filter options 

### ISSUE THREAD

**Issue by perryc85** [cs691projecthotspots/webapp#74]
For this issue, we need to filter our search for activities by country and state. We are already searching for the city.

**Comment by perryc85** [comment]
branch `activities-search`

**Comment by ChexWarrior** [comment]
@perryc85 You've successfully added the form fields, nice job.  Now you actually need to hook them into the database, checkout the method in the HomepageController to see how to grab the data from your fields.  You'll need to look into the activityRepo as well to make some queries.  It is a lot of work to do, so don't feel like you need to finish it all right now! We can work on this together over the weekend or Friday.

**Comment by perryc85** [comment]
`Look over Symfonycast on Doctrine`

**Comment by ChexWarrior** [comment]
@perryc85 

[Doctrine and the Database](https://symfonycasts.com/screencast/symfony-doctrine/install)

[Mastering Doctrine Relations](https://symfonycasts.com/screencast/doctrine-relations/comment-entity)
