### ISSUE TITLE
Ability to Delete User Account

### ISSUE THREAD

**Issue by ChexWarrior** [cs691projecthotspots/webapp#8]
* Allow admin user to delete user
* Allow a user to delete their own account
  * Would be a soft delete, a new field in database that indicates if this user was previously deleted. This would prevent them from re-registering this user.

**Comment by kd90693n** [comment]
Once the user submits the deletion request. It will confirm first if this is what they wish to do.

Copy: Are you sure you want to delete your account?

**Comment by ChexWarrior** [comment]
We've decided to perform a hard delete for this iteration.

**Comment by ChexWarrior** [comment]
@kd90693n I've begun working on this issue in the branch called **delete-user**.

**Comment by kd90693n** [comment]
Awesome, thank you! I'll pull this branch and test it when you let me know.

**Comment by ChexWarrior** [comment]
@kd90693n Had a break through this morning, I may be able to finish this before class today.

**Comment by kd90693n** [comment]
@ChexWarrior that is awesome, gives us more time to spend on the other two this coming weekend/week.
